In [1]:
#!pip install opencv-python

In [2]:
#Import thư viện
import cv2
import imgTools
import numpy as np

path = "C:/Users/hoang/Desktop/Image/architecture.jpg"
img = cv2.imread(path)

In [3]:
#In thông tin của ảnh
print(img)

[[[ 91  56  23]
  [ 91  56  23]
  [ 91  56  23]
  ...
  [105  67  32]
  [105  67  32]
  [105  67  32]]

 [[ 91  56  23]
  [ 91  56  23]
  [ 91  56  23]
  ...
  [105  67  32]
  [105  67  32]
  [105  67  32]]

 [[ 91  56  23]
  [ 91  56  23]
  [ 91  56  23]
  ...
  [105  67  32]
  [105  67  32]
  [105  67  32]]

 ...

 [[128 136 149]
  [128 136 149]
  [128 136 149]
  ...
  [231 227 226]
  [231 227 226]
  [232 228 227]]

 [[128 136 149]
  [128 136 149]
  [128 136 149]
  ...
  [231 227 226]
  [231 227 226]
  [232 228 227]]

 [[128 136 149]
  [128 136 149]
  [128 136 149]
  ...
  [231 227 226]
  [231 227 226]
  [232 228 227]]]


In [4]:
# Hiển thị kích thước hình ảnh
print(img.shape)
x, y, z = img.shape
print(x)
print(y)
print(z)

(846, 564, 3)
846
564
3


In [5]:
#Hiển thị hình ảnh
cv2.imshow("Animal", img)
#Chờ 1 khoảng thòi gian
cv2.waitKey(10000)
#Đóng cửa sổ
cv2.destroyWindow("Animal")

In [6]:
# Tách thành 3 màu
# b, g, r = cv2.split(img)
# cv2.imshow("Window", img)
# cv2.imshow("Red", r)
# cv2.imshow("Green", g)
# cv2.imshow("Blue", b)

# # Chờ một khoản thời gian
# cv2.waitKey(0)

# # Đóng toàn bộ cửa sổ
# cv2.destroyAllWindows()

In [7]:
# Chuyển ảnh gốc sang ảnh gray
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow("Ảnh gốc", img)
cv2.imshow("Ảnh xám", gray_img)
cv2.imshow("Ảnh âm bản", img_2)

# Chờ một khoản thời gian
cv2.waitKey(0)

# Đóng toàn bộ cửa sổ
cv2.destroyAllWindows()

In [8]:
# Thay đổi thông số điểm ảnh
height, width, z = img.shape
quater_h = height/2
quater_w = width/2

# Gradient color
green_color = (0, 255, 0)

#Copy ảnh
img2 = img.copy()

# Thay đổi màu của gốc 1/4 bên trái
for y in range(int(quater_h)):
    for x in range(int(quater_w)):
        img2[y, x] = green_color

# Bước 5: Hiển thị ảnh
cv2.imshow('Green (1/4 area)', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# Thay đổi thông số điểm ảnh 1/4 góc trên bên trên của tấm hình
height, width, z = img.shape
quater_h = height//2
quater_w = width//2

#Copy ảnh
img2 = img.copy()

# Gradient color
gradient = np.zeros_like(img2, dtype=np.uint8)

# Thay đổi màu của gốc 1/4 bên trái
for i in range(quater_w):  # Giới hạn trong 1/4 chiều ngang
    alpha = i / quater_w  # Tính tỷ lệ theo vị trí trong 1/4 chiều ngang
    color = (232 * (1 - alpha), 219, 252  * alpha)  # Tạo màu theo tỷ lệ
    gradient[:quater_h, i, :] = color  # Gán màu cho các cột trong 1/4 khu vực

# Bước 4: Trộn gradient với ảnh
blended_image = img2.copy()
blended_image[:quater_h, :quater_w] = cv2.addWeighted(
    img2[:quater_h, :quater_w], 0.5, 
    gradient[:quater_h, :quater_w], 0.5, 0
)

# Bước 5: Hiển thị ảnh
cv2.imshow('Gradient Image (1/4 area)', blended_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# Thay đổi thông số điểm ảnh toàn bộ tấm hình
height, width, z = img.shape
quater_h = height//2
quater_w = width//2

#Copy ảnh
img2 = img.copy()

# Gradient color
gradient = np.zeros_like(img2, dtype=np.uint8)

# Màu gradient từ #e8dbfc (RGB: 232, 219, 252) đến #f8f9d2 (RGB: 248, 249, 210)
start_color = np.array([252, 219, 232]) 
end_color = np.array([210, 249, 248]) 

for i in range(width):
    alpha = i / width  # Tính tỷ lệ giữa vị trí hiện tại và chiều rộng
    color = start_color * (1 - alpha) + end_color * alpha  # Tạo màu theo tỷ lệ
    gradient[:, i, :] = color  # Gán màu cho cột hiện tại

blended_image = cv2.addWeighted(img2, 0.5, gradient, 0.5, 0)

cv2.imshow('Gradient Image', blended_image)
cv2.waitKey(0)
cv2.destroyAllWindows()